version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: micronova_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: micronova_db
      MYSQL_USER: micronova_user
      MYSQL_PASSWORD: micronova_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
